# Generated by Django 3.2.7 on 2021-09-17 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UsersAuth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crypto',
            new_name='Certif',
        ),
        migrations.AlterField(
            model_name='message',
            name='document',
            field=models.FileField(upload_to='static/documents/'),
        ),
    ]
