# Generated by Django 3.2.7 on 2021-09-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sentfrom',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
