# Generated by Django 3.2.7 on 2021-09-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0002_auto_20210917_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='certif',
            name='recived',
            field=models.BooleanField(default=False),
        ),
    ]
