# Generated by Django 3.2.7 on 2021-09-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0003_message_sentfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='document',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
